version: '3.8'

services:
  web1:
    image: nginx:latest
    command: sh -c 'nginx -g "daemon off;"'
    networks:
      net2:
        ipv4_address: 193.168.1.2  # Specifying IP for web1 in net1 
      net3:
        ipv4_address: 194.168.1.3 
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Mount the custom config file
    ports:
      - "80:80"  # Localhost port 80 mapped to container port 80
      - "443:443"  # Expose HTTPS port
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=443

  web2:
    image: busybox:latest
    command: sh -c 'sleep infinity'
    networks:
      net2:
        ipv4_address: 193.168.1.3 

  web3:
    image: busybox:latest
    command: sh -c 'sleep infinity'
    networks:
      net3:
        ipv4_address: 194.168.1.4 

networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24  # Subnet for net1

  net2:
    driver: bridge
    ipam:
      config:
        - subnet: 193.168.1.0/24 

  net3:
    driver: bridge
    ipam:
      config:
        - subnet: 194.168.1.0/24  